import { join, resolve } from 'path';
import { mkdir, writeFile, exists } from 'fs/promises';

async function buildIOS() {
  const rootDir = resolve(import.meta.dir, '..');
  const entryPoint = process.argv[2] || 'examples/react-counter/app.tsx';
  const buildDir = join(rootDir, '.glyph-build', 'ios');
  const nativeDir = join(rootDir, 'native', 'ios');
  const resourceDir = join(nativeDir, 'GlyphShell', 'Resources');

  console.log('Building Glyph iOS app...');
  console.log(`  Entry: ${entryPoint}`);

  // Step 1: Create build directories
  await mkdir(buildDir, { recursive: true });
  await mkdir(resourceDir, { recursive: true });

  // Step 2: Create a wrapper entry that uses the iOS platform instead of web.
  // Instead of regex-transforming the app source (fragile), we read the app
  // source, strip the web-specific bootstrap (canvas setup, platform-web import,
  // direct render call), and prepend/append the iOS platform bootstrap.
  const iosEntryPath = join(buildDir, 'ios-entry.tsx');
  const resolvedAppEntry = resolve(rootDir, entryPoint);
  const appSource = await Bun.file(resolvedAppEntry).text();

  // Split the source into lines and filter out web-specific code
  const lines = appSource.split('\n');
  const filteredLines: string[] = [];
  let insideCanvasBlock = false;
  let braceDepth = 0;

  for (const line of lines) {
    // Skip the platform-web render import
    if (/import\s*\{[^}]*render[^}]*\}\s*from\s*['"][^'"]*platform-web['"]/.test(line)) {
      continue;
    }
    // Track and skip the `if (canvas) { ... }` block and preceding canvas setup
    if (/const\s+canvas\s*=/.test(line)) {
      continue;
    }
    if (/^\s*if\s*\(\s*canvas\s*\)/.test(line)) {
      insideCanvasBlock = true;
      braceDepth = 0;
    }
    if (insideCanvasBlock) {
      for (const ch of line) {
        if (ch === '{') braceDepth++;
        if (ch === '}') braceDepth--;
      }
      if (braceDepth <= 0 && line.includes('}')) {
        insideCanvasBlock = false;
      }
      continue;
    }
    filteredLines.push(line);
  }

  const iosEntrySource = `// iOS entry - generated by build-ios.ts
import { render } from '${resolve(rootDir, 'src/platform/ios.ts')}';
${filteredLines.join('\n')}

// Bootstrap: render the App component using the iOS native runtime
render(React.createElement(App, {}));
`;

  await writeFile(iosEntryPath, iosEntrySource);

  // Step 3: Bundle JS for iOS using Bun
  console.log('  Bundling JS...');
  const result = await Bun.build({
    entrypoints: [iosEntryPath],
    target: 'browser', // Closest to JSC environment
    format: 'esm',
    minify: true,
    define: {
      'process.env.NODE_ENV': '"production"',
    },
  });

  if (!result.success) {
    console.error('Bundle failed:');
    for (const log of result.logs) {
      console.error(' ', log.message);
    }
    process.exit(1);
  }

  const bundleJS = await result.outputs[0].text();

  // Write bundle to both build dir and native resources
  const bundlePath = join(buildDir, 'bundle.js');
  await writeFile(bundlePath, bundleJS);
  await writeFile(join(resourceDir, 'bundle.js'), bundleJS);
  console.log(`  Bundle: ${(bundleJS.length / 1024).toFixed(1)} KB`);

  // Step 4: Generate Xcode project if it does not exist
  const xcprojDir = join(nativeDir, 'GlyphShell.xcodeproj');
  const pbxprojPath = join(xcprojDir, 'project.pbxproj');

  if (!(await exists(pbxprojPath))) {
    console.log('  Generating Xcode project...');
    await mkdir(xcprojDir, { recursive: true });
    await writeFile(pbxprojPath, generatePbxproj());
  }

  // Step 5: Build with xcodebuild
  console.log('  Building native app...');
  const proc = Bun.spawn(
    [
      'xcodebuild',
      '-project',
      join(nativeDir, 'GlyphShell.xcodeproj'),
      '-scheme',
      'GlyphShell',
      '-destination',
      'platform=iOS Simulator,name=iPhone 15',
      '-derivedDataPath',
      join(buildDir, 'DerivedData'),
      'build',
    ],
    {
      cwd: nativeDir,
      stdout: 'pipe',
      stderr: 'pipe',
    },
  );

  const exitCode = await proc.exited;

  if (exitCode !== 0) {
    const stderr = await new Response(proc.stderr).text();
    console.error('xcodebuild failed:');
    const lines = stderr.split('\n');
    console.error(lines.slice(-30).join('\n'));
    process.exit(1);
  }

  const appPath = join(
    buildDir,
    'DerivedData',
    'Build',
    'Products',
    'Debug-iphonesimulator',
    'GlyphShell.app',
  );
  console.log('');
  console.log('  Build successful!');
  console.log(`  App: ${appPath}`);
  console.log('');
  console.log('  To run in simulator:');
  console.log('    xcrun simctl boot "iPhone 15"');
  console.log(`    xcrun simctl install booted "${appPath}"`);
  console.log('    xcrun simctl launch booted com.glyph.shell');
}

function generatePbxproj(): string {
  return `// !$*UTF8*$!
{
	archiveVersion = 1;
	classes = {
	};
	objectVersion = 56;
	objects = {

/* Begin PBXBuildFile section */
		A1000001 /* AppDelegate.swift in Sources */ = {isa = PBXBuildFile; fileRef = A2000001 /* AppDelegate.swift */; };
		A1000002 /* GlyphViewController.swift in Sources */ = {isa = PBXBuildFile; fileRef = A2000002 /* GlyphViewController.swift */; };
		A1000003 /* GlyphRenderView.swift in Sources */ = {isa = PBXBuildFile; fileRef = A2000003 /* GlyphRenderView.swift */; };
		A1000004 /* GlyphRuntime.swift in Sources */ = {isa = PBXBuildFile; fileRef = A2000004 /* GlyphRuntime.swift */; };
		A1000005 /* bundle.js in Resources */ = {isa = PBXBuildFile; fileRef = A2000005 /* bundle.js */; };
		A1000006 /* Assets.xcassets in Resources */ = {isa = PBXBuildFile; fileRef = A2000007 /* Assets.xcassets */; };
/* End PBXBuildFile section */

/* Begin PBXFileReference section */
		A2000001 /* AppDelegate.swift */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; path = AppDelegate.swift; sourceTree = "<group>"; };
		A2000002 /* GlyphViewController.swift */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; path = GlyphViewController.swift; sourceTree = "<group>"; };
		A2000003 /* GlyphRenderView.swift */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; path = GlyphRenderView.swift; sourceTree = "<group>"; };
		A2000004 /* GlyphRuntime.swift */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; path = GlyphRuntime.swift; sourceTree = "<group>"; };
		A2000005 /* bundle.js */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.javascript; path = bundle.js; sourceTree = "<group>"; };
		A2000006 /* Info.plist */ = {isa = PBXFileReference; lastKnownFileType = text.plist.xml; path = Info.plist; sourceTree = "<group>"; };
		A2000007 /* Assets.xcassets */ = {isa = PBXFileReference; lastKnownFileType = folder.assetcatalog; path = Assets.xcassets; sourceTree = "<group>"; };
		A2000010 /* GlyphShell.app */ = {isa = PBXFileReference; explicitFileType = wrapper.application; includeInIndex = 0; path = GlyphShell.app; sourceTree = BUILT_PRODUCTS_DIR; };
/* End PBXFileReference section */

/* Begin PBXFrameworksBuildPhase section */
		A4000003 /* Frameworks */ = {
			isa = PBXFrameworksBuildPhase;
			buildActionMask = 2147483647;
			files = (
			);
			runOnlyForDeploymentPostprocessing = 0;
		};
/* End PBXFrameworksBuildPhase section */

/* Begin PBXGroup section */
		A3000001 = {
			isa = PBXGroup;
			children = (
				A3000002 /* GlyphShell */,
				A3000003 /* Products */,
			);
			sourceTree = "<group>";
		};
		A3000002 /* GlyphShell */ = {
			isa = PBXGroup;
			children = (
				A2000001 /* AppDelegate.swift */,
				A2000002 /* GlyphViewController.swift */,
				A2000003 /* GlyphRenderView.swift */,
				A2000004 /* GlyphRuntime.swift */,
				A2000006 /* Info.plist */,
				A2000007 /* Assets.xcassets */,
				A3000004 /* Resources */,
			);
			path = GlyphShell;
			sourceTree = "<group>";
		};
		A3000003 /* Products */ = {
			isa = PBXGroup;
			children = (
				A2000010 /* GlyphShell.app */,
			);
			name = Products;
			sourceTree = "<group>";
		};
		A3000004 /* Resources */ = {
			isa = PBXGroup;
			children = (
				A2000005 /* bundle.js */,
			);
			path = Resources;
			sourceTree = "<group>";
		};
/* End PBXGroup section */

/* Begin PBXNativeTarget section */
		A5000001 /* GlyphShell */ = {
			isa = PBXNativeTarget;
			buildConfigurationList = A7000001 /* Build configuration list for PBXNativeTarget "GlyphShell" */;
			buildPhases = (
				A4000001 /* Sources */,
				A4000002 /* Resources */,
				A4000003 /* Frameworks */,
			);
			buildRules = (
			);
			dependencies = (
			);
			name = GlyphShell;
			productName = GlyphShell;
			productReference = A2000010 /* GlyphShell.app */;
			productType = "com.apple.product-type.application";
		};
/* End PBXNativeTarget section */

/* Begin PBXProject section */
		A6000001 /* Project object */ = {
			isa = PBXProject;
			attributes = {
				BuildIndependentTargetsInParallel = 1;
				LastSwiftUpdateCheck = 1540;
				LastUpgradeCheck = 1540;
			};
			buildConfigurationList = A7000002 /* Build configuration list for PBXProject "GlyphShell" */;
			compatibilityVersion = "Xcode 14.0";
			developmentRegion = en;
			hasScannedForEncodings = 0;
			knownRegions = (
				en,
				Base,
			);
			mainGroup = A3000001;
			productRefGroup = A3000003 /* Products */;
			projectDirPath = "";
			projectRoot = "";
			targets = (
				A5000001 /* GlyphShell */,
			);
		};
/* End PBXProject section */

/* Begin PBXResourcesBuildPhase section */
		A4000002 /* Resources */ = {
			isa = PBXResourcesBuildPhase;
			buildActionMask = 2147483647;
			files = (
				A1000005 /* bundle.js in Resources */,
				A1000006 /* Assets.xcassets in Resources */,
			);
			runOnlyForDeploymentPostprocessing = 0;
		};
/* End PBXResourcesBuildPhase section */

/* Begin PBXSourcesBuildPhase section */
		A4000001 /* Sources */ = {
			isa = PBXSourcesBuildPhase;
			buildActionMask = 2147483647;
			files = (
				A1000001 /* AppDelegate.swift in Sources */,
				A1000002 /* GlyphViewController.swift in Sources */,
				A1000003 /* GlyphRenderView.swift in Sources */,
				A1000004 /* GlyphRuntime.swift in Sources */,
			);
			runOnlyForDeploymentPostprocessing = 0;
		};
/* End PBXSourcesBuildPhase section */

/* Begin XCBuildConfiguration section */
		A8000001 /* Debug */ = {
			isa = XCBuildConfiguration;
			buildSettings = {
				ASSETCATALOG_COMPILER_APPICON_NAME = AppIcon;
				CODE_SIGN_STYLE = Automatic;
				INFOPLIST_FILE = GlyphShell/Info.plist;
				IPHONEOS_DEPLOYMENT_TARGET = 15.0;
				LD_RUNPATH_SEARCH_PATHS = (
					"$(inherited)",
					"@executable_path/Frameworks",
				);
				PRODUCT_BUNDLE_IDENTIFIER = com.glyph.shell;
				PRODUCT_NAME = "$(TARGET_NAME)";
				SWIFT_VERSION = 5.0;
				TARGETED_DEVICE_FAMILY = "1,2";
			};
			name = Debug;
		};
		A8000002 /* Release */ = {
			isa = XCBuildConfiguration;
			buildSettings = {
				ASSETCATALOG_COMPILER_APPICON_NAME = AppIcon;
				CODE_SIGN_STYLE = Automatic;
				INFOPLIST_FILE = GlyphShell/Info.plist;
				IPHONEOS_DEPLOYMENT_TARGET = 15.0;
				LD_RUNPATH_SEARCH_PATHS = (
					"$(inherited)",
					"@executable_path/Frameworks",
				);
				PRODUCT_BUNDLE_IDENTIFIER = com.glyph.shell;
				PRODUCT_NAME = "$(TARGET_NAME)";
				SWIFT_OPTIMIZATION_LEVEL = "-O";
				SWIFT_VERSION = 5.0;
				TARGETED_DEVICE_FAMILY = "1,2";
			};
			name = Release;
		};
		A8000003 /* Debug */ = {
			isa = XCBuildConfiguration;
			buildSettings = {
				ALWAYS_SEARCH_USER_PATHS = NO;
				CLANG_ANALYZER_NONNULL = YES;
				CLANG_ANALYZER_NUMBER_OBJECT_CONVERSION = YES_AGGRESSIVE;
				CLANG_CXX_LANGUAGE_STANDARD = "gnu++20";
				CLANG_ENABLE_MODULES = YES;
				CLANG_ENABLE_OBJC_ARC = YES;
				CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING = YES;
				CLANG_WARN_BOOL_CONVERSION = YES;
				CLANG_WARN_COMMA = YES;
				CLANG_WARN_CONSTANT_CONVERSION = YES;
				CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS = YES;
				CLANG_WARN_DIRECT_OBJC_ISA_USAGE = YES_ERROR;
				CLANG_WARN_DOCUMENTATION_COMMENTS = YES;
				CLANG_WARN_EMPTY_BODY = YES;
				CLANG_WARN_ENUM_CONVERSION = YES;
				CLANG_WARN_INFINITE_RECURSION = YES;
				CLANG_WARN_INT_CONVERSION = YES;
				CLANG_WARN_NON_LITERAL_NULL_CONVERSION = YES;
				CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF = YES;
				CLANG_WARN_OBJC_LITERAL_CONVERSION = YES;
				CLANG_WARN_OBJC_ROOT_CLASS = YES_ERROR;
				CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER = YES;
				CLANG_WARN_RANGE_LOOP_ANALYSIS = YES;
				CLANG_WARN_STRICT_PROTOTYPES = YES;
				CLANG_WARN_SUSPICIOUS_MOVE = YES;
				CLANG_WARN_UNGUARDED_AVAILABILITY = YES_AGGRESSIVE;
				CLANG_WARN_UNREACHABLE_CODE = YES;
				CLANG_WARN__DUPLICATE_METHOD_MATCH = YES;
				CODE_SIGN_IDENTITY = "-";
				COPY_PHASE_STRIP = NO;
				DEBUG_INFORMATION_FORMAT = dwarf;
				ENABLE_STRICT_OBJC_MSGSEND = YES;
				ENABLE_TESTABILITY = YES;
				GCC_C_LANGUAGE_STANDARD = gnu17;
				GCC_DYNAMIC_NO_PIC = NO;
				GCC_NO_COMMON_BLOCKS = YES;
				GCC_OPTIMIZATION_LEVEL = 0;
				GCC_PREPROCESSOR_DEFINITIONS = (
					"DEBUG=1",
					"$(inherited)",
				);
				GCC_WARN_64_TO_32_BIT_CONVERSION = YES;
				GCC_WARN_ABOUT_RETURN_TYPE = YES_ERROR;
				GCC_WARN_UNDECLARED_SELECTOR = YES;
				GCC_WARN_UNINITIALIZED_AUTOS = YES_AGGRESSIVE;
				GCC_WARN_UNUSED_FUNCTION = YES;
				GCC_WARN_UNUSED_VARIABLE = YES;
				MTL_ENABLE_DEBUG_INFO = INCLUDE_SOURCE;
				MTL_FAST_MATH = YES;
				ONLY_ACTIVE_ARCH = YES;
				SDKROOT = iphoneos;
				SWIFT_ACTIVE_COMPILATION_CONDITIONS = "$(inherited) DEBUG";
				SWIFT_OPTIMIZATION_LEVEL = "-Onone";
			};
			name = Debug;
		};
		A8000004 /* Release */ = {
			isa = XCBuildConfiguration;
			buildSettings = {
				ALWAYS_SEARCH_USER_PATHS = NO;
				CLANG_ANALYZER_NONNULL = YES;
				CLANG_ANALYZER_NUMBER_OBJECT_CONVERSION = YES_AGGRESSIVE;
				CLANG_CXX_LANGUAGE_STANDARD = "gnu++20";
				CLANG_ENABLE_MODULES = YES;
				CLANG_ENABLE_OBJC_ARC = YES;
				CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING = YES;
				CLANG_WARN_BOOL_CONVERSION = YES;
				CLANG_WARN_COMMA = YES;
				CLANG_WARN_CONSTANT_CONVERSION = YES;
				CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS = YES;
				CLANG_WARN_DIRECT_OBJC_ISA_USAGE = YES_ERROR;
				CLANG_WARN_DOCUMENTATION_COMMENTS = YES;
				CLANG_WARN_EMPTY_BODY = YES;
				CLANG_WARN_ENUM_CONVERSION = YES;
				CLANG_WARN_INFINITE_RECURSION = YES;
				CLANG_WARN_INT_CONVERSION = YES;
				CLANG_WARN_NON_LITERAL_NULL_CONVERSION = YES;
				CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF = YES;
				CLANG_WARN_OBJC_LITERAL_CONVERSION = YES;
				CLANG_WARN_OBJC_ROOT_CLASS = YES_ERROR;
				CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER = YES;
				CLANG_WARN_RANGE_LOOP_ANALYSIS = YES;
				CLANG_WARN_STRICT_PROTOTYPES = YES;
				CLANG_WARN_SUSPICIOUS_MOVE = YES;
				CLANG_WARN_UNGUARDED_AVAILABILITY = YES_AGGRESSIVE;
				CLANG_WARN_UNREACHABLE_CODE = YES;
				CLANG_WARN__DUPLICATE_METHOD_MATCH = YES;
				CODE_SIGN_IDENTITY = "-";
				COPY_PHASE_STRIP = NO;
				DEBUG_INFORMATION_FORMAT = "dwarf-with-dsym";
				ENABLE_NS_ASSERTIONS = NO;
				ENABLE_STRICT_OBJC_MSGSEND = YES;
				GCC_C_LANGUAGE_STANDARD = gnu17;
				GCC_NO_COMMON_BLOCKS = YES;
				GCC_OPTIMIZATION_LEVEL = s;
				GCC_WARN_64_TO_32_BIT_CONVERSION = YES;
				GCC_WARN_ABOUT_RETURN_TYPE = YES_ERROR;
				GCC_WARN_UNDECLARED_SELECTOR = YES;
				GCC_WARN_UNINITIALIZED_AUTOS = YES_AGGRESSIVE;
				GCC_WARN_UNUSED_FUNCTION = YES;
				GCC_WARN_UNUSED_VARIABLE = YES;
				MTL_ENABLE_DEBUG_INFO = NO;
				MTL_FAST_MATH = YES;
				SDKROOT = iphoneos;
				SWIFT_COMPILATION_MODE = wholemodule;
				VALIDATE_PRODUCT = YES;
			};
			name = Release;
		};
/* End XCBuildConfiguration section */

/* Begin XCConfigurationList section */
		A7000001 /* Build configuration list for PBXNativeTarget "GlyphShell" */ = {
			isa = XCConfigurationList;
			buildConfigurations = (
				A8000001 /* Debug */,
				A8000002 /* Release */,
			);
			defaultConfigurationIsVisible = 0;
			defaultConfigurationName = Release;
		};
		A7000002 /* Build configuration list for PBXProject "GlyphShell" */ = {
			isa = XCConfigurationList;
			buildConfigurations = (
				A8000003 /* Debug */,
				A8000004 /* Release */,
			);
			defaultConfigurationIsVisible = 0;
			defaultConfigurationName = Release;
		};
/* End XCConfigurationList section */

	};
	rootObject = A6000001 /* Project object */;
}
`;
}

buildIOS().catch(console.error);
