import { resolve, join } from 'path';
import { mkdir, writeFile, exists } from 'fs/promises';

async function buildAndroid() {
  const rootDir = resolve(import.meta.dir, '..');
  const entryPoint = process.argv[2] || 'examples/calculator/app.ts';
  const buildDir = join(rootDir, '.glyphis-build', 'android');
  const nativeDir = join(rootDir, 'native', 'android');
  const assetsDir = join(nativeDir, 'app', 'src', 'main', 'assets');

  console.log('Building Glyphis Android app...');
  console.log(`  Entry: ${entryPoint}`);

  await mkdir(buildDir, { recursive: true });
  await mkdir(assetsDir, { recursive: true });

  // Create native entry: strip web bootstrap, inject native platform
  const nativeEntryPath = join(buildDir, 'native-entry.ts');
  const resolvedAppEntry = resolve(rootDir, entryPoint);
  const appSource = await Bun.file(resolvedAppEntry).text();

  const lines = appSource.split('\n');
  const filtered: string[] = [];
  let skipBlock = false;
  let braceDepth = 0;

  for (const line of lines) {
    if (/createWebPlatform/.test(line) && /import/.test(line)) {
      // Remove only createWebPlatform from the import, keep everything else
      filtered.push(line.replace(/,?\s*createWebPlatform/, ''));
      continue;
    }
    if (/getElementById.*glyphis-root/.test(line)) continue;
    if (/^\s*if\s*\(\s*canvas\s*\)/.test(line)) {
      skipBlock = true;
      braceDepth = 0;
    }
    if (skipBlock) {
      for (const ch of line) {
        if (ch === '{') braceDepth++;
        if (ch === '}') braceDepth--;
      }
      if (braceDepth <= 0 && line.includes('}')) skipBlock = false;
      continue;
    }
    if (/const\s+platform\s*=\s*createWebPlatform/.test(line)) continue;
    if (/^\s*render\(/.test(line) && /platform\)/.test(line)) continue;
    filtered.push(line);
  }

  // Resolve relative imports in the app source to absolute paths
  // (the native entry lives in .glyphis-build/android/, not the app's directory)
  const appDir = resolve(rootDir, entryPoint, '..');
  const resolvedSource = filtered.join('\n').replace(
    /from\s+['"](\.[^'"]+)['"]/g,
    (match, relPath) => `from '${resolve(appDir, relPath)}'`
  );

  const nativeEntrySource = `// Native entry — generated by build-android.ts
import { createNativePlatform } from '${resolve(rootDir, 'src/platform/native')}';
${resolvedSource}

// Bootstrap with native platform
const __platform = createNativePlatform();
render(() => glyphisRenderer.createComponent(App, {}), __platform);
`;

  await writeFile(nativeEntryPath, nativeEntrySource);

  // Bundle with Bun.build — redirect yoga-layout to yoga-native.ts (no WASM)
  console.log('  Bundling JS...');
  const result = await Bun.build({
    entrypoints: [nativeEntryPath],
    target: 'browser',
    format: 'esm',
    minify: true,
    plugins: [{
      name: 'yoga-native',
      setup(build) {
        build.onResolve({ filter: /^yoga-layout/ }, () => ({
          path: resolve(rootDir, 'src/yoga-native.ts'),
        }));
      },
    }],
    define: {
      'process.env.NODE_ENV': '"production"',
      'import.meta.url': '""',
    },
  });

  if (!result.success) {
    console.error('Bundle failed:');
    for (const log of result.logs) console.error(' ', log.message);
    process.exit(1);
  }

  const raw = await result.outputs[0].text();
  // No async IIFE needed — yoga-native is synchronous (no WASM, no TLA)
  const bundleJS = raw;
  const outBundlePath = join(assetsDir, 'bundle.js');
  await writeFile(outBundlePath, bundleJS);
  await writeFile(join(buildDir, 'bundle.js'), bundleJS);
  console.log(`  Bundle: ${(bundleJS.length / 1024).toFixed(1)} KB`);

  // Check for Gradle wrapper
  const gradlewPath = join(nativeDir, 'gradlew');
  if (!(await exists(gradlewPath))) {
    console.log('\n  Gradle wrapper not found. Run:');
    console.log(`    cd ${nativeDir}`);
    console.log('    gradle wrapper');
    console.log(`\n  Bundle saved to: ${outBundlePath}`);
    return;
  }

  // Build APK
  console.log('  Building APK...');
  const gradleProc = Bun.spawn([
    join(nativeDir, 'gradlew'),
    'assembleDebug',
  ], {
    cwd: nativeDir,
    stdout: 'pipe',
    stderr: 'pipe',
    env: {
      ...process.env,
      ANDROID_HOME: process.env.ANDROID_HOME || join(process.env.HOME!, 'Library', 'Android', 'sdk'),
    },
  });

  const gradleExitCode = await gradleProc.exited;
  if (gradleExitCode !== 0) {
    const stderr = await new Response(gradleProc.stderr).text();
    console.error('Gradle build failed:');
    console.error(stderr.split('\n').slice(-15).join('\n'));
    process.exit(1);
  }

  const apkPath = join(nativeDir, 'app', 'build', 'outputs', 'apk', 'debug', 'app-debug.apk');
  console.log('\n  Build successful!');
  console.log(`  APK: ${apkPath}\n`);
  console.log('  To install on emulator:');
  console.log(`    adb install ${apkPath}`);
}

buildAndroid().catch(console.error);
