import { resolve, join } from 'path';
import { mkdir, writeFile } from 'fs/promises';

/**
 * Strip web-specific bootstrap from an app source file.
 * Removes createWebPlatform imports, canvas setup, and the
 * conditional web render block.
 */
export function stripWebBootstrap(appSource: string): string {
  var lines = appSource.split('\n');
  var filtered: string[] = [];
  var skipBlock = false;
  var braceDepth = 0;

  for (var i = 0; i < lines.length; i++) {
    var line = lines[i];
    if (/createWebPlatform/.test(line) && /import/.test(line)) {
      // Remove only createWebPlatform from the import, keep everything else
      filtered.push(line.replace(/,?\s*createWebPlatform/, ''));
      continue;
    }
    if (/getElementById.*glyphis-root/.test(line)) continue;
    if (/^\s*if\s*\(\s*canvas\s*\)/.test(line)) {
      skipBlock = true;
      braceDepth = 0;
    }
    if (skipBlock) {
      for (var j = 0; j < line.length; j++) {
        if (line[j] === '{') braceDepth++;
        if (line[j] === '}') braceDepth--;
      }
      if (braceDepth <= 0 && line.includes('}')) skipBlock = false;
      continue;
    }
    if (/const\s+platform\s*=\s*createWebPlatform/.test(line)) continue;
    if (/^\s*render\(/.test(line) && /platform\)/.test(line)) continue;
    filtered.push(line);
  }

  return filtered.join('\n');
}

/**
 * Resolve relative imports in source code to absolute paths.
 * Needed because the native entry file lives in a build directory,
 * not the app's source directory.
 */
export function resolveRelativeImports(source: string, appDir: string): string {
  return source.replace(
    /from\s+['"](\.[^'"]+)['"]/g,
    function(_match: string, relPath: string) {
      return "from '" + resolve(appDir, relPath) + "'";
    }
  );
}

/**
 * Create a native entry file from an app source.
 * Strips web bootstrap, resolves imports, and generates the
 * native entry with platform injection.
 */
export async function createNativeEntry(opts: {
  rootDir: string;
  entryPoint: string;
  buildDir: string;
  scriptName: string;
}): Promise<{ entryPath: string; source: string }> {
  var rootDir = opts.rootDir;
  var entryPoint = opts.entryPoint;
  var buildDir = opts.buildDir;
  var scriptName = opts.scriptName;

  await mkdir(buildDir, { recursive: true });

  var nativeEntryPath = join(buildDir, 'native-entry.ts');
  var appSource = await Bun.file(resolve(rootDir, entryPoint)).text();

  var strippedSource = stripWebBootstrap(appSource);

  var appDir = resolve(rootDir, entryPoint, '..');
  var resolvedSource = resolveRelativeImports(strippedSource, appDir);

  var nativeEntrySource = '// Native entry \u2014 generated by ' + scriptName + '\n'
    + "import { createNativePlatform } from '" + resolve(rootDir, 'src/platform/native') + "';\n"
    + resolvedSource + '\n'
    + '\n'
    + 'const __platform = createNativePlatform();\n'
    + 'render(() => glyphisRenderer.createComponent(App, {}), __platform);\n';

  await writeFile(nativeEntryPath, nativeEntrySource);

  return { entryPath: nativeEntryPath, source: nativeEntrySource };
}

/**
 * Bundle JS for a native target using Bun.build.
 * Redirects yoga-layout to yoga-native.ts (no WASM).
 */
export async function bundleForNative(opts: {
  entryPath: string;
  rootDir: string;
  minify: boolean;
  extraDefine?: Record<string, string>;
}): Promise<string> {
  var rootDir = opts.rootDir;
  var define: Record<string, string> = {
    'process.env.NODE_ENV': '"production"',
  };
  if (opts.extraDefine) {
    var keys = Object.keys(opts.extraDefine);
    for (var i = 0; i < keys.length; i++) {
      define[keys[i]] = opts.extraDefine[keys[i]];
    }
  }

  var result = await Bun.build({
    entrypoints: [opts.entryPath],
    target: 'browser',
    format: 'esm',
    minify: opts.minify,
    plugins: [{
      name: 'yoga-native',
      setup: function(build) {
        build.onResolve({ filter: /^yoga-layout/ }, function() {
          return {
            path: resolve(rootDir, 'src/yoga-native.ts'),
          };
        });
      },
    }],
    define: define,
  });

  if (!result.success) {
    console.error('Bundle failed:');
    for (var j = 0; j < result.logs.length; j++) {
      console.error(' ', result.logs[j].message);
    }
    process.exit(1);
  }

  return await result.outputs[0].text();
}
