#include "bridge_common.h"

/* ------------------------------------------------------------------ */
/*  Register polyfills: setTimeout, queueMicrotask, MessageChannel,   */
/*  performance.now, requestAnimationFrame, fetch, WebSocket,         */
/*  localStorage, URL, btoa/atob, TextEncoder/TextDecoder, crypto,    */
/*  AbortController                                                   */
/*                                                                    */
/*  All internal state is closure-scoped via IIFEs to prevent         */
/*  accidental or malicious modification from app code.               */
/* ------------------------------------------------------------------ */

void register_polyfills(JSContextRef ctx, JSObjectRef global) {
    const char* polyfills =

        /* performance.now (IIFE-scoped start time) */
        "(function() {"
        "  var startTime = Date.now();"
        "  globalThis.performance = { now: function() { return Date.now() - startTime; } };"
        "})();"

        /* setTimeout / clearTimeout / setInterval / clearInterval (IIFE-scoped counter) */
        "(function() {"
        "  var nextId = 1;"
        "  globalThis.setTimeout = function(callback, delay) {"
        "    var id = nextId++;"
        "    __glyphis_native.scheduleTimer(id, delay || 0, callback);"
        "    return id;"
        "  };"
        "  globalThis.clearTimeout = function(id) {};"
        "  globalThis.setInterval = function(callback, interval) {"
        "    var id = nextId++;"
        "    function tick() {"
        "      callback();"
        "      __glyphis_native.scheduleTimer(id, interval, tick);"
        "    }"
        "    __glyphis_native.scheduleTimer(id, interval, tick);"
        "    return id;"
        "  };"
        "  globalThis.clearInterval = globalThis.clearTimeout;"
        "})();"

        /* requestAnimationFrame / cancelAnimationFrame */
        "globalThis.requestAnimationFrame = function(callback) {"
        "  return setTimeout(function() { callback(performance.now()); }, 16);"
        "};"
        "globalThis.cancelAnimationFrame = globalThis.clearTimeout;"

        /* queueMicrotask */
        "if (typeof queueMicrotask === 'undefined') {"
        "  globalThis.queueMicrotask = function(cb) { setTimeout(cb, 0); };"
        "}"

        /* MessageChannel */
        "if (typeof MessageChannel === 'undefined') {"
        "  globalThis.MessageChannel = function() {"
        "    this.port1 = { onmessage: null };"
        "    var self = this;"
        "    this.port2 = {"
        "      postMessage: function(msg) {"
        "        if (self.port1.onmessage) {"
        "          var h = self.port1.onmessage;"
        "          setTimeout(function() { h({ data: msg }); }, 0);"
        "        }"
        "      }"
        "    };"
        "  };"
        "}"

        /* fetch (IIFE-scoped callbacks map) */
        "(function() {"
        "  var nextId = 1;"
        "  var callbacks = {};"
        "  globalThis.fetch = function(url, options) {"
        "    return new Promise(function(resolve, reject) {"
        "      var reqId = nextId++;"
        "      callbacks[reqId] = { resolve: resolve, reject: reject };"
        "      var method = (options && options.method) || 'GET';"
        "      var headers = (options && options.headers) || {};"
        "      var body = (options && options.body) || '';"
        "      __glyphis_native.fetch(reqId, url, method, JSON.stringify(headers), body);"
        "    });"
        "  };"
        "  globalThis.__glyphis_onFetchResponse = function(reqId, status, headersJson, body) {"
        "    var cb = callbacks[reqId];"
        "    if (!cb) return;"
        "    delete callbacks[reqId];"
        "    var headers = {};"
        "    try { headers = JSON.parse(headersJson); } catch(e) {}"
        "    var response = {"
        "      ok: status >= 200 && status < 300,"
        "      status: status,"
        "      statusText: '',"
        "      headers: {"
        "        get: function(name) { return headers[name.toLowerCase()] || null; },"
        "        has: function(name) { return name.toLowerCase() in headers; }"
        "      },"
        "      text: function() { return Promise.resolve(body); },"
        "      json: function() { return Promise.resolve(JSON.parse(body)); },"
        "      clone: function() { return response; }"
        "    };"
        "    cb.resolve(response);"
        "  };"
        "  globalThis.__glyphis_onFetchError = function(reqId, message) {"
        "    var cb = callbacks[reqId];"
        "    if (!cb) return;"
        "    delete callbacks[reqId];"
        "    cb.reject(new Error(message));"
        "  };"
        "})();"

        /* localStorage (IIFE-scoped storage) */
        "(function() {"
        "  var store = {};"
        "  var data = __glyphis_native.storageGetAll();"
        "  if (data) { try { store = JSON.parse(data); } catch(e) {} }"
        "  globalThis.localStorage = {"
        "    getItem: function(key) { return store[key] !== undefined ? store[key] : null; },"
        "    setItem: function(key, value) { store[key] = String(value); __glyphis_native.storageSet(key, String(value)); },"
        "    removeItem: function(key) { delete store[key]; __glyphis_native.storageRemove(key); },"
        "    clear: function() { store = {}; __glyphis_native.storageClear(); },"
        "    get length() { return Object.keys(store).length; },"
        "    key: function(i) { var keys = Object.keys(store); return keys[i] !== undefined ? keys[i] : null; }"
        "  };"
        "})();"

        /* URLSearchParams (no mutable state, pure constructor) */
        "globalThis.URLSearchParams = function(search) {"
        "  var params = {};"
        "  if (search) {"
        "    var s = String(search).replace(/^\\?/, '');"
        "    var pairs = s.split('&');"
        "    for (var i = 0; i < pairs.length; i++) {"
        "      var parts = pairs[i].split('=');"
        "      if (parts[0]) params[decodeURIComponent(parts[0])] = decodeURIComponent(parts[1] || '');"
        "    }"
        "  }"
        "  this._params = params;"
        "  this.get = function(name) { return this._params[name] !== undefined ? this._params[name] : null; };"
        "  this.has = function(name) { return name in this._params; };"
        "  this.set = function(name, value) { this._params[name] = String(value); };"
        "  this['delete'] = function(name) { delete this._params[name]; };"
        "  this.toString = function() {"
        "    var keys = Object.keys(this._params);"
        "    var parts = [];"
        "    for (var i = 0; i < keys.length; i++) {"
        "      parts.push(encodeURIComponent(keys[i]) + '=' + encodeURIComponent(this._params[keys[i]]));"
        "    }"
        "    return parts.join('&');"
        "  };"
        "};"

        /* URL (no mutable state, pure constructor) */
        "globalThis.URL = function(url, base) {"
        "  if (base) {"
        "    if (url.indexOf('://') === -1) {"
        "      url = base.replace(/\\/[^\\/]*$/, '/') + url;"
        "    }"
        "  }"
        "  var match = url.match(/^(https?:)\\/\\/([^\\/\\?#]+)(\\/[^?#]*)?(\\?[^#]*)?(#.*)?$/);"
        "  if (!match) throw new TypeError('Invalid URL: ' + url);"
        "  this.protocol = match[1] || '';"
        "  this.host = match[2] || '';"
        "  this.hostname = this.host.split(':')[0];"
        "  this.port = this.host.split(':')[1] || '';"
        "  this.pathname = match[3] || '/';"
        "  this.search = match[4] || '';"
        "  this.hash = match[5] || '';"
        "  this.origin = this.protocol + '//' + this.host;"
        "  this.href = url;"
        "  this.searchParams = new URLSearchParams(this.search);"
        "};"
        "URL.prototype.toString = function() { return this.href; };"

        /* btoa / atob (IIFE-scoped charset) */
        "(function() {"
        "  var chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';"
        "  globalThis.btoa = function(str) {"
        "    var out = '';"
        "    for (var i = 0; i < str.length; i += 3) {"
        "      var c1 = str.charCodeAt(i);"
        "      var c2 = i+1 < str.length ? str.charCodeAt(i+1) : 0;"
        "      var c3 = i+2 < str.length ? str.charCodeAt(i+2) : 0;"
        "      out += chars[c1 >> 2];"
        "      out += chars[((c1 & 3) << 4) | (c2 >> 4)];"
        "      out += i+1 < str.length ? chars[((c2 & 15) << 2) | (c3 >> 6)] : '=';"
        "      out += i+2 < str.length ? chars[c3 & 63] : '=';"
        "    }"
        "    return out;"
        "  };"
        "  globalThis.atob = function(str) {"
        "    str = str.replace(/=/g, '');"
        "    var out = '';"
        "    for (var i = 0; i < str.length; i += 4) {"
        "      var c1 = chars.indexOf(str[i]);"
        "      var c2 = chars.indexOf(str[i+1]);"
        "      var c3 = i+2 < str.length ? chars.indexOf(str[i+2]) : 0;"
        "      var c4 = i+3 < str.length ? chars.indexOf(str[i+3]) : 0;"
        "      out += String.fromCharCode((c1 << 2) | (c2 >> 4));"
        "      if (i+2 < str.length) out += String.fromCharCode(((c2 & 15) << 4) | (c3 >> 2));"
        "      if (i+3 < str.length) out += String.fromCharCode(((c3 & 3) << 6) | c4);"
        "    }"
        "    return out;"
        "  };"
        "})();"

        /* TextEncoder / TextDecoder (no mutable state) */
        "globalThis.TextEncoder = function() {};"
        "TextEncoder.prototype.encode = function(str) {"
        "  var utf8 = [];"
        "  for (var i = 0; i < str.length; i++) {"
        "    var c = str.charCodeAt(i);"
        "    if (c < 128) { utf8.push(c); }"
        "    else if (c < 2048) { utf8.push(192 | (c >> 6), 128 | (c & 63)); }"
        "    else { utf8.push(224 | (c >> 12), 128 | ((c >> 6) & 63), 128 | (c & 63)); }"
        "  }"
        "  return new Uint8Array(utf8);"
        "};"
        "globalThis.TextDecoder = function() {};"
        "TextDecoder.prototype.decode = function(buf) {"
        "  var arr = new Uint8Array(buf);"
        "  var str = '';"
        "  for (var i = 0; i < arr.length; ) {"
        "    var c = arr[i];"
        "    if (c < 128) { str += String.fromCharCode(c); i++; }"
        "    else if (c < 224) { str += String.fromCharCode(((c & 31) << 6) | (arr[i+1] & 63)); i += 2; }"
        "    else { str += String.fromCharCode(((c & 15) << 12) | ((arr[i+1] & 63) << 6) | (arr[i+2] & 63)); i += 3; }"
        "  }"
        "  return str;"
        "};"

        /* crypto.getRandomValues (not cryptographically secure) */
        "globalThis.crypto = {"
        "  getRandomValues: function(arr) {"
        "    for (var i = 0; i < arr.length; i++) {"
        "      arr[i] = Math.floor(Math.random() * 256);"
        "    }"
        "    return arr;"
        "  }"
        "};"

        /* AbortController (no mutable shared state) */
        "globalThis.AbortController = function() {"
        "  this.signal = { aborted: false, reason: undefined };"
        "  var self = this;"
        "  this.abort = function(reason) {"
        "    self.signal.aborted = true;"
        "    self.signal.reason = reason || new Error('AbortError');"
        "  };"
        "};"

        /* WebSocket (IIFE-scoped instances map) */
        "(function() {"
        "  var nextId = 1;"
        "  var instances = {};"
        "  globalThis.WebSocket = function(url, protocols) {"
        "    var wsId = nextId++;"
        "    this._wsId = wsId;"
        "    this.url = url;"
        "    this.readyState = 0;"
        "    this.onopen = null;"
        "    this.onmessage = null;"
        "    this.onclose = null;"
        "    this.onerror = null;"
        "    instances[wsId] = this;"
        "    __glyphis_native.wsConnect(wsId, url, protocols || '');"
        "  };"
        "  WebSocket.CONNECTING = 0;"
        "  WebSocket.OPEN = 1;"
        "  WebSocket.CLOSING = 2;"
        "  WebSocket.CLOSED = 3;"
        "  WebSocket.prototype.send = function(data) {"
        "    if (this.readyState !== 1) throw new Error('WebSocket is not open');"
        "    __glyphis_native.wsSend(this._wsId, String(data));"
        "  };"
        "  WebSocket.prototype.close = function(code, reason) {"
        "    if (this.readyState >= 2) return;"
        "    this.readyState = 2;"
        "    __glyphis_native.wsClose(this._wsId, code || 1000, reason || '');"
        "  };"
        "  globalThis.__glyphis_onWsOpen = function(wsId) {"
        "    var ws = instances[wsId];"
        "    if (!ws) return;"
        "    ws.readyState = 1;"
        "    if (ws.onopen) ws.onopen({ type: 'open' });"
        "  };"
        "  globalThis.__glyphis_onWsMessage = function(wsId, data) {"
        "    var ws = instances[wsId];"
        "    if (!ws) return;"
        "    if (ws.onmessage) ws.onmessage({ type: 'message', data: data });"
        "  };"
        "  globalThis.__glyphis_onWsClose = function(wsId, code, reason) {"
        "    var ws = instances[wsId];"
        "    if (!ws) return;"
        "    ws.readyState = 3;"
        "    if (ws.onclose) ws.onclose({ type: 'close', code: code, reason: reason, wasClean: code === 1000 });"
        "    delete instances[wsId];"
        "  };"
        "  globalThis.__glyphis_onWsError = function(wsId, message) {"
        "    var ws = instances[wsId];"
        "    if (!ws) return;"
        "    if (ws.onerror) ws.onerror({ type: 'error', message: message });"
        "  };"
        "})();"
    ;

    JSStringRef polyfillStr = CStringToJSString(polyfills);
    JSValueRef exception = NULL;
    JSEvaluateScript(ctx, polyfillStr, NULL, NULL, 0, &exception);
    if (exception) {
        JSStringRef exStr = JSValueToStringCopy(ctx, exception, NULL);
        char* msg = JSStringToCString(exStr);
        LOGE("[JS Error] polyfill init: %s", msg);
        free(msg);
        JSStringRelease(exStr);
    }
    JSStringRelease(polyfillStr);
}
