#include "bridge_common.h"

/* ------------------------------------------------------------------ */
/*  Register polyfills: setTimeout, queueMicrotask, MessageChannel,   */
/*  performance.now, requestAnimationFrame                            */
/* ------------------------------------------------------------------ */

void register_polyfills(JSContextRef ctx, JSObjectRef global) {
    const char* polyfills =
        /* performance.now */
        "var __glyphis_startTime = Date.now();"
        "var performance = { now: function() { return Date.now() - __glyphis_startTime; } };"

        /* setTimeout / clearTimeout / setInterval / clearInterval
           (defined first so queueMicrotask and MessageChannel can use setTimeout) */
        "var __glyphis_nextTimerId = 1;"
        ""
        "globalThis.setTimeout = function(callback, delay) {"
        "  var id = __glyphis_nextTimerId++;"
        "  __glyphis_native.scheduleTimer(id, delay || 0, callback);"
        "  return id;"
        "};"
        ""
        "globalThis.clearTimeout = function(id) {};"
        ""
        "globalThis.setInterval = function(callback, interval) {"
        "  var id = __glyphis_nextTimerId++;"
        "  function tick() {"
        "    callback();"
        "    __glyphis_native.scheduleTimer(id, interval, tick);"
        "  }"
        "  __glyphis_native.scheduleTimer(id, interval, tick);"
        "  return id;"
        "};"
        ""
        "globalThis.clearInterval = globalThis.clearTimeout;"
        ""
        /* requestAnimationFrame / cancelAnimationFrame */
        "globalThis.requestAnimationFrame = function(callback) {"
        "  return setTimeout(function() { callback(performance.now()); }, 16);"
        "};"
        ""
        "globalThis.cancelAnimationFrame = globalThis.clearTimeout;"
        ""
        /* queueMicrotask -- use setTimeout(cb, 0) instead of Promise.resolve().then()
           to ensure the microtask is dispatched via the native timer loop */
        "if (typeof queueMicrotask === 'undefined') {"
        "  globalThis.queueMicrotask = function(cb) { setTimeout(cb, 0); };"
        "}"
        ""
        /* MessageChannel */
        "if (typeof MessageChannel === 'undefined') {"
        "  function MessageChannel() {"
        "    this.port1 = { onmessage: null };"
        "    var self = this;"
        "    this.port2 = {"
        "      postMessage: function(msg) {"
        "        if (self.port1.onmessage) {"
        "          var h = self.port1.onmessage;"
        "          setTimeout(function() { h({ data: msg }); }, 0);"
        "        }"
        "      }"
        "    };"
        "  }"
        "  globalThis.MessageChannel = MessageChannel;"
        "}"

        /* fetch polyfill */
        "var __glyphis_nextFetchId = 1;"
        "var __glyphis_fetchCallbacks = {};"
        ""
        "globalThis.fetch = function(url, options) {"
        "  return new Promise(function(resolve, reject) {"
        "    var reqId = __glyphis_nextFetchId++;"
        "    __glyphis_fetchCallbacks[reqId] = { resolve: resolve, reject: reject };"
        "    var method = (options && options.method) || 'GET';"
        "    var headers = (options && options.headers) || {};"
        "    var body = (options && options.body) || '';"
        "    __glyphis_native.fetch(reqId, url, method, JSON.stringify(headers), body);"
        "  });"
        "};"
        ""
        "globalThis.__glyphis_onFetchResponse = function(reqId, status, headersJson, body) {"
        "  var cb = __glyphis_fetchCallbacks[reqId];"
        "  if (!cb) return;"
        "  delete __glyphis_fetchCallbacks[reqId];"
        "  var headers = {};"
        "  try { headers = JSON.parse(headersJson); } catch(e) {}"
        "  var response = {"
        "    ok: status >= 200 && status < 300,"
        "    status: status,"
        "    statusText: '',"
        "    headers: {"
        "      get: function(name) { return headers[name.toLowerCase()] || null; },"
        "      has: function(name) { return name.toLowerCase() in headers; }"
        "    },"
        "    text: function() { return Promise.resolve(body); },"
        "    json: function() { return Promise.resolve(JSON.parse(body)); },"
        "    clone: function() { return response; }"
        "  };"
        "  cb.resolve(response);"
        "};"
        ""
        "globalThis.__glyphis_onFetchError = function(reqId, message) {"
        "  var cb = __glyphis_fetchCallbacks[reqId];"
        "  if (!cb) return;"
        "  delete __glyphis_fetchCallbacks[reqId];"
        "  cb.reject(new Error(message));"
        "};"

        /* localStorage (backed by native SharedPreferences) */
        "var __storage = {};"
        "globalThis.localStorage = {"
        "  getItem: function(key) { return __storage[key] || null; },"
        "  setItem: function(key, value) { __storage[key] = String(value); __glyphis_native.storageSet(key, String(value)); },"
        "  removeItem: function(key) { delete __storage[key]; __glyphis_native.storageRemove(key); },"
        "  clear: function() { __storage = {}; __glyphis_native.storageClear(); },"
        "  get length() { return Object.keys(__storage).length; },"
        "  key: function(i) { var keys = Object.keys(__storage); return keys[i] || null; }"
        "};"
        "var __storedData = __glyphis_native.storageGetAll();"
        "if (__storedData) { try { __storage = JSON.parse(__storedData); } catch(e) {} }"

        /* URLSearchParams */
        "globalThis.URLSearchParams = function(search) {"
        "  var params = {};"
        "  if (search) {"
        "    var s = String(search).replace(/^\\?/, '');"
        "    var pairs = s.split('&');"
        "    for (var i = 0; i < pairs.length; i++) {"
        "      var parts = pairs[i].split('=');"
        "      if (parts[0]) params[decodeURIComponent(parts[0])] = decodeURIComponent(parts[1] || '');"
        "    }"
        "  }"
        "  this._params = params;"
        "  this.get = function(name) { return this._params[name] !== undefined ? this._params[name] : null; };"
        "  this.has = function(name) { return name in this._params; };"
        "  this.set = function(name, value) { this._params[name] = String(value); };"
        "  this['delete'] = function(name) { delete this._params[name]; };"
        "  this.toString = function() {"
        "    var keys = Object.keys(this._params);"
        "    var parts = [];"
        "    for (var i = 0; i < keys.length; i++) {"
        "      parts.push(encodeURIComponent(keys[i]) + '=' + encodeURIComponent(this._params[keys[i]]));"
        "    }"
        "    return parts.join('&');"
        "  };"
        "};"

        /* URL */
        "globalThis.URL = function(url, base) {"
        "  if (base) {"
        "    if (url.indexOf('://') === -1) {"
        "      url = base.replace(/\\/[^\\/]*$/, '/') + url;"
        "    }"
        "  }"
        "  var match = url.match(/^(https?:)\\/\\/([^\\/\\?#]+)(\\/[^?#]*)?(\\?[^#]*)?(#.*)?$/);"
        "  if (!match) throw new TypeError('Invalid URL: ' + url);"
        "  this.protocol = match[1] || '';"
        "  this.host = match[2] || '';"
        "  this.hostname = this.host.split(':')[0];"
        "  this.port = this.host.split(':')[1] || '';"
        "  this.pathname = match[3] || '/';"
        "  this.search = match[4] || '';"
        "  this.hash = match[5] || '';"
        "  this.origin = this.protocol + '//' + this.host;"
        "  this.href = url;"
        "  this.searchParams = new URLSearchParams(this.search);"
        "};"
        "URL.prototype.toString = function() { return this.href; };"

        /* btoa / atob (Base64) */
        "var __b64chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';"
        "globalThis.btoa = function(str) {"
        "  var out = '';"
        "  for (var i = 0; i < str.length; i += 3) {"
        "    var c1 = str.charCodeAt(i);"
        "    var c2 = i+1 < str.length ? str.charCodeAt(i+1) : 0;"
        "    var c3 = i+2 < str.length ? str.charCodeAt(i+2) : 0;"
        "    out += __b64chars[c1 >> 2];"
        "    out += __b64chars[((c1 & 3) << 4) | (c2 >> 4)];"
        "    out += i+1 < str.length ? __b64chars[((c2 & 15) << 2) | (c3 >> 6)] : '=';"
        "    out += i+2 < str.length ? __b64chars[c3 & 63] : '=';"
        "  }"
        "  return out;"
        "};"
        "globalThis.atob = function(str) {"
        "  str = str.replace(/=/g, '');"
        "  var out = '';"
        "  for (var i = 0; i < str.length; i += 4) {"
        "    var c1 = __b64chars.indexOf(str[i]);"
        "    var c2 = __b64chars.indexOf(str[i+1]);"
        "    var c3 = i+2 < str.length ? __b64chars.indexOf(str[i+2]) : 0;"
        "    var c4 = i+3 < str.length ? __b64chars.indexOf(str[i+3]) : 0;"
        "    out += String.fromCharCode((c1 << 2) | (c2 >> 4));"
        "    if (i+2 < str.length) out += String.fromCharCode(((c2 & 15) << 4) | (c3 >> 2));"
        "    if (i+3 < str.length) out += String.fromCharCode(((c3 & 3) << 6) | c4);"
        "  }"
        "  return out;"
        "};"

        /* TextEncoder / TextDecoder (UTF-8 only) */
        "globalThis.TextEncoder = function() {};"
        "TextEncoder.prototype.encode = function(str) {"
        "  var utf8 = [];"
        "  for (var i = 0; i < str.length; i++) {"
        "    var c = str.charCodeAt(i);"
        "    if (c < 128) { utf8.push(c); }"
        "    else if (c < 2048) { utf8.push(192 | (c >> 6), 128 | (c & 63)); }"
        "    else { utf8.push(224 | (c >> 12), 128 | ((c >> 6) & 63), 128 | (c & 63)); }"
        "  }"
        "  return new Uint8Array(utf8);"
        "};"
        "globalThis.TextDecoder = function() {};"
        "TextDecoder.prototype.decode = function(buf) {"
        "  var arr = new Uint8Array(buf);"
        "  var str = '';"
        "  for (var i = 0; i < arr.length; ) {"
        "    var c = arr[i];"
        "    if (c < 128) { str += String.fromCharCode(c); i++; }"
        "    else if (c < 224) { str += String.fromCharCode(((c & 31) << 6) | (arr[i+1] & 63)); i += 2; }"
        "    else { str += String.fromCharCode(((c & 15) << 12) | ((arr[i+1] & 63) << 6) | (arr[i+2] & 63)); i += 3; }"
        "  }"
        "  return str;"
        "};"

        /* crypto.getRandomValues (Math.random based -- not cryptographically secure) */
        "globalThis.crypto = {"
        "  getRandomValues: function(arr) {"
        "    for (var i = 0; i < arr.length; i++) {"
        "      arr[i] = Math.floor(Math.random() * 256);"
        "    }"
        "    return arr;"
        "  }"
        "};"

        /* AbortController / AbortSignal */
        "globalThis.AbortController = function() {"
        "  this.signal = { aborted: false, reason: undefined };"
        "  var self = this;"
        "  this.abort = function(reason) {"
        "    self.signal.aborted = true;"
        "    self.signal.reason = reason || new Error('AbortError');"
        "  };"
        "};"
    ;

    JSStringRef polyfillStr = CStringToJSString(polyfills);
    JSValueRef exception = NULL;
    JSEvaluateScript(ctx, polyfillStr, NULL, NULL, 0, &exception);
    if (exception) {
        JSStringRef exStr = JSValueToStringCopy(ctx, exception, NULL);
        char* msg = JSStringToCString(exStr);
        LOGE("[JS Error] polyfill init: %s", msg);
        free(msg);
        JSStringRelease(exStr);
    }
    JSStringRelease(polyfillStr);
}
